### ISSUE TITLE
parcel data in infowindow popup

### ISSUE THREAD

**Issue by ericoneal** [LouisvilleWaterCompany/SPIN#61]

**Comment by LouisvilleWaterCompany** [comment]
Pull new LOJIC data from:
https://ags1i.lojic.org/arcgis/rest/services/LOJIC/Parcel/MapServer/exts/ParcelRestSoe/GetReport?token=&LRSN=52565&f=json&dojo.preventCache=1507233878270

and parse JSON to modal or the like

**Comment by LouisvilleWaterCompany** [comment]
Move Search2 service with parcels to gisprod
